name: Linux build

on:
  push:
    branches:
      - 'main'
      - 'dev'
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install build dependencies
      run: make install-build-dependencies-deb

    - name: Build linux-bin
      run: make linux-bin

    - name: Build unittester
      run: make unittester-bin

    - name: Run unit tests
      run: make run-unittester
